#pragma config(Sensor, S1,     distance,       sensorSONAR)
#pragma config(Sensor, S2,     lightA,         sensorLightActive)
#pragma config(Sensor, S3,     lightB,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "wait.h";

/**
 * Line follower proporzionale (con margine di errore) utilizzando i metodi della libreria wait.
 *
 * @author Bryan Beffa
 * @author Matteo Forni
 * @version 11.01.2019
 */
task main()
{
	while(){
		//margine consentito
		double margin = 0.7;

		//soglia di luce riflessa
		int threshold = 50;

		//calcolo l'errore
		int errorA = threshold - SensorValue(lightA);
		int errorB = threshold - SensorValue(lightB);

		//calcolo la velocità
		double speedA = errorA * margin;
		double speedB = errorB * margin;

		//setto la velocità al motore collegato alla porta A e alla porta B
		motor[motorA] = speedA;
		motor[motorB] = speedB;
		waitTime(100);
	}
}
