#pragma config(Sensor, S1,     distance,       sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "wait.h";
task main()
{
	/**
	 * waitTouch			funziona check
	 * waitLight			funziona check
	 * waitDistance		funziona check
	 * waitSound			funziona check
	 * waitTime				funziona check
	 * waitRotations 	funziona check
	 * waitDegrees 		funziona check
	 */

	//waitRotations(0, 10, 30);
	//while(true){writeDebugStreamLine("%d", SensorValue[distance];wait1Msec(100);}
	//motor[motorA] = 50;
	//waitLight(S1, 50, true);
	//motor[motorA] = 50;
	//waitLight(S1, 20, false);

	motor[motorA] = 40;
	waitDistance(distance, 100);
}
