#pragma config(Sensor, S1,     luce,           sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "wait.h"
task main()
{

	waitRotations(0, 10, 30);
	//while(true){writeDebugStreamLine("%d", SensorValue(sonar));wait(1);}
	//waitDistance(sonar, 15);
}
